"""initial schema

Revision ID: b5e047e8f3c4
Revises:
Create Date: 2026-04-21 21:21:31.235109

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b5e047e8f3c4"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "role", sa.Enum("landlord", "tenant", name="user_role_enum"), nullable=False
        ),
        sa.Column(
            "full_name", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True
        ),
        sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
        sa.Column(
            "password_hash",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("consent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_table(
        "audit_logs",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column(
            "actor_role", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False
        ),
        sa.Column("landlord_id", sa.Uuid(), nullable=False),
        sa.Column(
            "entity_type", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column(
            "action", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column("before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("note", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["users.id"], name=op.f("fk_audit_logs_actor_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["landlord_id"], ["users.id"], name=op.f("fk_audit_logs_landlord_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_table(
        "notifications",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("recipient_id", sa.Uuid(), nullable=False),
        sa.Column(
            "event_key", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column(
            "title", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False
        ),
        sa.Column("body", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "entity_type", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True
        ),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("read_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["recipient_id"],
            ["users.id"],
            name=op.f("fk_notifications_recipient_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_table(
        "password_reset_tokens",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "token_hash", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_password_reset_tokens_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_password_reset_tokens")),
    )
    op.create_index(
        op.f("ix_password_reset_tokens_token_hash"),
        "password_reset_tokens",
        ["token_hash"],
        unique=True,
    )
    op.create_table(
        "properties",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column(
            "address", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True
        ),
        sa.Column("billing_day", sa.Integer(), nullable=False),
        sa.Column("landlord_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "billing_day BETWEEN 1 AND 28",
            name=op.f("ck_properties_ck_properties_billing_day_range"),
        ),
        sa.ForeignKeyConstraint(
            ["landlord_id"], ["users.id"], name=op.f("fk_properties_landlord_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_properties")),
    )
    op.create_table(
        "refresh_tokens",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "token_hash", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rotated_to_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["rotated_to_id"],
            ["refresh_tokens.id"],
            name=op.f("fk_refresh_tokens_rotated_to_id_refresh_tokens"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_refresh_tokens_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
    )
    op.create_index(
        op.f("ix_refresh_tokens_token_hash"),
        "refresh_tokens",
        ["token_hash"],
        unique=True,
    )
    op.create_table(
        "tenants",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "full_name", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False
        ),
        sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column(
            "id_card_number", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True
        ),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column(
            "hometown", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True
        ),
        sa.Column("note", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("move_out_date", sa.Date(), nullable=True),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("anonymized_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("landlord_id", sa.Uuid(), nullable=False),
        sa.Column("promoted_from_occupant_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["landlord_id"], ["users.id"], name=op.f("fk_tenants_landlord_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["promoted_from_occupant_id"],
            ["occupants.id"],
            name="fk_tenants_promoted_from_occupant_id_occupants",
            ondelete="SET NULL",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_tenants_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenants")),
    )
    op.create_table(
        "invite_tokens",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "invited_email",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=False,
        ),
        sa.Column(
            "token_hash", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_invite_tokens_created_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_invite_tokens_tenant_id_tenants"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invite_tokens")),
    )
    op.create_index(
        op.f("ix_invite_tokens_token_hash"),
        "invite_tokens",
        ["token_hash"],
        unique=True,
    )
    op.create_table(
        "occupants",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column(
            "full_name", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False
        ),
        sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
        sa.Column(
            "id_card_number", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True
        ),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column(
            "relationship", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True
        ),
        sa.Column("note", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("moved_in_date", sa.Date(), nullable=False),
        sa.Column("moved_out_date", sa.Date(), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_occupants_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_occupants")),
    )
    op.create_table(
        "rooms",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "display_name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column("default_rent", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("max_occupants", sa.Integer(), nullable=True),
        sa.Column("property_id", sa.Uuid(), nullable=False),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("archived_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "max_occupants IS NULL OR max_occupants > 0",
            name=op.f("ck_rooms_ck_rooms_max_occupants_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["properties.id"],
            name=op.f("fk_rooms_property_id_properties"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rooms")),
    )
    op.create_table(
        "services",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column(
            "billing_type",
            sa.Enum("per_meter", "per_person", "fixed", name="billing_type_enum"),
            nullable=False,
        ),
        sa.Column("price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("unit", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
        sa.Column(
            "scope",
            sa.Enum("all_rooms", "selected_rooms", name="service_scope_enum"),
            server_default="all_rooms",
            nullable=False,
        ),
        sa.Column(
            "meter_scope",
            sa.Enum("shared", "per_room", name="meter_scope_enum"),
            nullable=True,
        ),
        sa.Column("property_id", sa.Uuid(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "\n            (billing_type = 'per_meter' AND unit IS NOT NULL AND meter_scope IS NOT NULL)\n            OR\n            (billing_type != 'per_meter' AND unit IS NULL AND meter_scope IS NULL)\n            ",
            name=op.f("ck_services_ck_services_per_meter_fields_consistency"),
        ),
        sa.CheckConstraint(
            "price >= 0", name=op.f("ck_services_ck_services_price_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["properties.id"],
            name=op.f("fk_services_property_id_properties"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_services")),
    )
    op.create_table(
        "leases",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("rent_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("deposit_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("billing_day", sa.Integer(), nullable=False),
        sa.Column("note", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("room_id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("terminated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "terminated_reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "deposit_status",
            sa.Enum(
                "held", "returned", "forfeited", "deducted", name="deposit_status_enum"
            ),
            server_default="held",
            nullable=False,
        ),
        sa.Column("deposit_settled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "deposit_settlement_note", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.CheckConstraint(
            "billing_day BETWEEN 1 AND 28",
            name=op.f("ck_leases_ck_leases_billing_day_range"),
        ),
        sa.CheckConstraint(
            "deposit_amount >= 0", name=op.f("ck_leases_ck_leases_deposit_non_negative")
        ),
        sa.CheckConstraint(
            "end_date >= start_date", name=op.f("ck_leases_ck_leases_end_after_start")
        ),
        sa.CheckConstraint(
            "rent_amount >= 0", name=op.f("ck_leases_ck_leases_rent_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["room_id"], ["rooms.id"], name=op.f("fk_leases_room_id_rooms")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_leases_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_leases")),
    )
    op.create_table(
        "meter_readings",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("reading_value", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("reading_date", sa.Date(), nullable=False),
        sa.Column("note", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("service_id", sa.Uuid(), nullable=False),
        sa.Column("room_id", sa.Uuid(), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "reading_value >= 0",
            name=op.f("ck_meter_readings_ck_meter_readings_value_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_meter_readings_created_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["room_id"], ["rooms.id"], name=op.f("fk_meter_readings_room_id_rooms")
        ),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.id"],
            name=op.f("fk_meter_readings_service_id_services"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meter_readings")),
    )
    op.create_table(
        "service_rooms",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column("service_id", sa.Uuid(), nullable=False),
        sa.Column("room_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["room_id"], ["rooms.id"], name=op.f("fk_service_rooms_room_id_rooms")
        ),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.id"],
            name=op.f("fk_service_rooms_service_id_services"),
        ),
        sa.PrimaryKeyConstraint("service_id", "room_id", name=op.f("pk_service_rooms")),
    )
    op.create_table(
        "invoices",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("billing_month", sa.Date(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("note", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("lease_id", sa.Uuid(), nullable=False),
        sa.Column("landlord_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "invoice_number",
            sqlmodel.sql.sqltypes.AutoString(length=30),
            nullable=False,
        ),
        sa.Column("voided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "voided_reason",
            sa.Enum(
                "wrong_meter_reading",
                "wrong_rent",
                "wrong_service_config",
                "tenant_dispute",
                "duplicate",
                "other",
                name="voided_reason_enum",
            ),
            nullable=True,
        ),
        sa.Column("void_note", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("voided_by_user_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "\n            (voided_at IS NULL AND voided_reason IS NULL AND voided_by_user_id IS NULL)\n            OR\n            (voided_at IS NOT NULL AND voided_reason IS NOT NULL AND voided_by_user_id IS NOT NULL)\n            ",
            name=op.f("ck_invoices_ck_invoices_void_fields_consistency"),
        ),
        sa.CheckConstraint(
            "total_amount >= 0", name=op.f("ck_invoices_ck_invoices_total_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_invoices_created_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["landlord_id"], ["users.id"], name=op.f("fk_invoices_landlord_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["lease_id"], ["leases.id"], name=op.f("fk_invoices_lease_id_leases")
        ),
        sa.ForeignKeyConstraint(
            ["voided_by_user_id"],
            ["users.id"],
            name=op.f("fk_invoices_voided_by_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invoices")),
    )
    op.create_table(
        "invoice_line_items",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "line_type",
            sa.Enum("rent", "service", "adjustment", name="line_type_enum"),
            nullable=False,
        ),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False
        ),
        sa.Column("unit", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
        sa.Column("billing_period_start", sa.Date(), nullable=False),
        sa.Column("billing_period_end", sa.Date(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("unit_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("invoice_id", sa.Uuid(), nullable=False),
        sa.Column("service_id", sa.Uuid(), nullable=True),
        sa.Column("meter_reading_start_id", sa.Uuid(), nullable=True),
        sa.Column("meter_reading_end_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "\n            (line_type = 'service' AND service_id IS NOT NULL)\n            OR\n            (line_type IN ('rent', 'adjustment') AND service_id IS NULL)\n            ",
            name=op.f("ck_invoice_line_items_ck_line_items_service_id_consistency"),
        ),
        sa.CheckConstraint(
            "line_type = 'adjustment' OR amount >= 0",
            name=op.f(
                "ck_invoice_line_items_ck_line_items_amount_non_negative_non_adjustment"
            ),
        ),
        sa.CheckConstraint(
            "billing_period_end >= billing_period_start",
            name=op.f("ck_invoice_line_items_ck_line_items_period_end_after_start"),
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoices.id"],
            name=op.f("fk_invoice_line_items_invoice_id_invoices"),
        ),
        sa.ForeignKeyConstraint(
            ["meter_reading_end_id"],
            ["meter_readings.id"],
            name=op.f("fk_invoice_line_items_meter_reading_end_id_meter_readings"),
        ),
        sa.ForeignKeyConstraint(
            ["meter_reading_start_id"],
            ["meter_readings.id"],
            name=op.f("fk_invoice_line_items_meter_reading_start_id_meter_readings"),
        ),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.id"],
            name=op.f("fk_invoice_line_items_service_id_services"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invoice_line_items")),
    )
    op.create_table(
        "payments",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("paid_at", sa.Date(), nullable=False),
        sa.Column(
            "method",
            sa.Enum(
                "cash", "bank_transfer", "ewallet", "other", name="payment_method_enum"
            ),
            nullable=False,
        ),
        sa.Column(
            "reference", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True
        ),
        sa.Column("note", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("invoice_id", sa.Uuid(), nullable=False),
        sa.Column("recorded_by_user_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "amount > 0", name=op.f("ck_payments_ck_payments_amount_strict_positive")
        ),
        sa.CheckConstraint(
            "paid_at <= CURRENT_DATE",
            name=op.f("ck_payments_ck_payments_paid_at_not_future"),
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoices.id"],
            name=op.f("fk_payments_invoice_id_invoices"),
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by_user_id"],
            ["users.id"],
            name=op.f("fk_payments_recorded_by_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("payments")
    op.drop_table("invoice_line_items")
    op.drop_table("invoices")
    op.drop_table("service_rooms")
    op.drop_table("meter_readings")
    op.drop_table("leases")
    op.drop_table("services")
    op.drop_table("rooms")
    op.drop_table("occupants")
    op.drop_index(op.f("ix_invite_tokens_token_hash"), table_name="invite_tokens")
    op.drop_table("invite_tokens")
    op.drop_table("tenants")
    op.drop_index(op.f("ix_refresh_tokens_token_hash"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_table("properties")
    op.drop_index(
        op.f("ix_password_reset_tokens_token_hash"), table_name="password_reset_tokens"
    )
    op.drop_table("password_reset_tokens")
    op.drop_table("notifications")
    op.drop_table("audit_logs")
    op.drop_table("users")
    # Drop PG enum types (autogen không handle — xem S3.2 notes)
    for enum_name in (
        "user_role_enum",
        "billing_type_enum",
        "service_scope_enum",
        "meter_scope_enum",
        "deposit_status_enum",
        "voided_reason_enum",
        "line_type_enum",
        "payment_method_enum",
    ):
        op.execute(f"DROP TYPE {enum_name}")
    # ### end Alembic commands ###
